filebeat.inputs:

- type: log
  enabled: true
  
  paths:
    - /usr/src/petshop/petshop.log

  multiline.pattern: ^\d{2,4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}
  multiline.negate: true
  multiline.match: after

#============================= Filebeat modules ===============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#================================ General =====================================
tags: ["backend"]

fields:
  ver: "APP_VER"

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:5044"]

#================================ Procesors =====================================

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["elasticsearch:9200"]
