version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VER}
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/backup:/opt/backup
    ports:
      - 9200:9200
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VER}
    ports:
      - 5601:5601
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VER}
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/
    restart: always

volumes:
  esdata:
    driver: local
